import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { FileText, Download, Plus, RefreshCw } from 'lucide-react';
import ReportCard from '../components/Reports/ReportCard';
import LoadingSpinner from '../components/common/LoadingSpinner';
import { formatDate } from '../utils/formatters';
import costService from '../services/costService';
import toast from 'react-hot-toast';

const MOCK_REPORTS = [
  { id: 1, name: 'June 2025 Cost Summary',          reportType: 'CostSummary',     status: 'completed', generatedAt: new Date(Date.now() - 86400000).toISOString() },
  { id: 2, name: 'Resource Usage Report - Q2 2025', reportType: 'ResourceUsage',   status: 'completed', generatedAt: new Date(Date.now() - 172800000).toISOString() },
  { id: 3, name: 'Optimization Opportunities',      reportType: 'Recommendations', status: 'completed', generatedAt: new Date(Date.now() - 259200000).toISOString() },
  { id: 4, name: 'May 2025 Budget Analysis',        reportType: 'BudgetAnalysis',  status: 'completed', generatedAt: new Date(Date.now() - 345600000).toISOString() },
  { id: 5, name: 'Compliance Report - June 2025',   reportType: 'Compliance',      status: 'completed', generatedAt: new Date(Date.now() - 432000000).toISOString() },
];

const REPORT_TYPES = [
  { type: 'CostSummary',     label: 'Cost Summary',         description: 'Monthly cost breakdown by service and region' },
  { type: 'ResourceUsage',   label: 'Resource Usage',       description: 'Detailed utilization metrics for all resources' },
  { type: 'Recommendations', label: 'Recommendations',      description: 'Optimization opportunities and savings report' },
  { type: 'BudgetAnalysis',  label: 'Budget Analysis',      description: 'Budget vs. actual spend comparison' },
  { type: 'Compliance',      label: 'Compliance',           description: 'Governance and compliance status report' },
];

function downloadReportAsPDF(report) {
  try {
    const content = [
      `AZURE COST MONITOR - ${report.name}`,
      '='.repeat(60),
      `Report Type: ${report.reportType}`,
      `Generated: ${formatDate(report.generatedAt)}`,
      `Status: ${report.status}`,
      '',
      'This report was generated by Azure Cost Monitor.',
      'For full report data, please connect to the backend API.',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  } catch {
    toast.error('Download failed');
  }
}

export default function Reports() {
  const qc = useQueryClient();
  const [generating, setGenerating] = useState(null);

  const { data, isLoading } = useQuery({
    queryKey: ['reports'],
    queryFn: costService.getReports,
    retry: 1,
  });

  const generateMutation = useMutation({
    mutationFn: costService.generateReport,
    onSuccess: () => {
      toast.success('Report generation started! It will appear in the list shortly.');
      qc.invalidateQueries({ queryKey: ['reports'] });
      setGenerating(null);
    },
    onError: () => {
      toast.error('Failed to generate report');
      setGenerating(null);
    },
  });

  const reports = Array.isArray(data) && data.length > 0 ? data : MOCK_REPORTS;

  function handleGenerate(type) {
    setGenerating(type);
    generateMutation.mutate(type);
  }

  return (
    <div style={{ padding: '24px', maxWidth: '1200px', animation: 'fadeIn 0.35s ease' }}>
      {/* Generate section */}
      <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: '12px', padding: '24px', marginBottom: '24px' }}>
        <h2 style={{ color: 'var(--text-primary)', fontWeight: '700', fontSize: '1rem', marginBottom: '4px' }}>Generate New Report</h2>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem', marginBottom: '20px' }}>Select a report type to generate a new report</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '12px' }}>
          {REPORT_TYPES.map(({ type, label, description }) => (
            <button
              key={type}
              onClick={() => handleGenerate(type)}
              disabled={generating === type || generateMutation.isPending}
              style={{
                padding: '14px 16px',
                background: generating === type ? 'rgba(59,130,246,0.15)' : 'var(--bg-tertiary)',
                border: `1px solid ${generating === type ? 'rgba(59,130,246,0.4)' : 'var(--border-color)'}`,
                borderRadius: '10px',
                cursor: generating ? 'not-allowed' : 'pointer',
                textAlign: 'left',
                transition: 'all 0.15s',
                opacity: generating && generating !== type ? 0.6 : 1,
              }}
              onMouseEnter={(e) => { if (!generating) { e.currentTarget.style.background = 'var(--border-color)'; e.currentTarget.style.borderColor = '#3b82f666'; } }}
              onMouseLeave={(e) => { e.currentTarget.style.background = 'var(--bg-tertiary)'; e.currentTarget.style.borderColor = 'var(--border-color)'; }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                {generating === type ? (
                  <span className="spinner spinner-sm" style={{ width: '16px', height: '16px' }} />
                ) : (
                  <FileText size={16} color="#3b82f6" />
                )}
                <span style={{ color: 'var(--text-primary)', fontWeight: '600', fontSize: '0.85rem' }}>{label}</span>
              </div>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.75rem', lineHeight: 1.4 }}>{description}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Reports list */}
      <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: '12px', padding: '24px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
          <div>
            <h2 style={{ color: 'var(--text-primary)', fontWeight: '700', fontSize: '1rem', marginBottom: '4px' }}>Generated Reports</h2>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{reports.length} reports available</p>
          </div>
          <button
            onClick={() => qc.invalidateQueries({ queryKey: ['reports'] })}
            style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 14px', background: 'var(--bg-tertiary)', border: '1px solid var(--border-color)', borderRadius: '8px', cursor: 'pointer', fontSize: '0.82rem', color: 'var(--text-secondary)', fontFamily: 'inherit' }}
          >
            <RefreshCw size={13} /> Refresh
          </button>
        </div>

        {isLoading ? (
          <LoadingSpinner size="md" text="Loading reports…" />
        ) : reports.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px', color: 'var(--text-muted)' }}>
            <FileText size={40} style={{ margin: '0 auto 12px', display: 'block', opacity: 0.3 }} />
            <p>No reports yet. Generate one above.</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {reports.map((report) => (
              <ReportCard
                key={report.id}
                report={report}
                onDownload={downloadReportAsPDF}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
